# Generated by Django 5.2.1 on 2025-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_festival_regionofmeghalaya_trevalaround"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionofmeghalaya",
            name="name",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="regionofmeghalaya",
            name="region_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
