# Generated by Django 5.2.1 on 2025-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_regionofmeghalaya_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionofmeghalaya",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
