# Generated by Django 5.2.1 on 2025-06-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_regionofmeghalaya_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
