# Generated by Django 5.2.1 on 2025-06-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_festival_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meghalyavideos",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
