# Generated by Django 5.2.1 on 2025-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_meghalyavideos_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trevalaround",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
