# Generated by Django 5.2.1 on 2025-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_trevalaround_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trevalaround",
            name="place",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
