# Generated by Django 5.2.1 on 2025-07-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_trevalaround_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeghalayaLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "placeUrl",
                    models.URLField(
                        blank=True,
                        default="https://example.com",
                        help_text="Enter the official website of the place",
                        max_length=300,
                        null=True,
                        verbose_name="Place Website",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
