# Generated by Django 6.0.3 on 2026-03-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_contactmessage_messagereply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rickshaw", "Auto Rickshaw"),
                            ("taxi", "Taxi"),
                            ("car", "Car"),
                            ("bus", "Bus"),
                            ("bike", "Bike"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_name",
                    models.CharField(
                        help_text="e.g., Maruti Swift, Honda Activa", max_length=100
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=20, unique=True)),
                (
                    "vehicle_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("cng", "CNG"),
                            ("electric", "Electric"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                ("seating_capacity", models.PositiveIntegerField(default=4)),
                ("ac_available", models.BooleanField(default=False)),
                ("price_per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "base_fare",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum fare",
                        max_digits=10,
                    ),
                ),
                ("vehicle_photo_1", models.ImageField(upload_to="vehicles/")),
                (
                    "vehicle_photo_2",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "vehicle_photo_3",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "registration_certificate",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicles/documents/"
                    ),
                ),
                (
                    "insurance_document",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicles/documents/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                ("return_trip", models.BooleanField(default=False)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("passenger_name", models.CharField(max_length=100)),
                ("passenger_phone", models.CharField(max_length=15)),
                (
                    "passenger_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("number_of_passengers", models.PositiveIntegerField(default=1)),
                ("special_requests", models.TextField(blank=True, null=True)),
                (
                    "estimated_distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Payment Pending"),
                            ("submitted", "Payment Submitted"),
                            ("verified", "Payment Verified"),
                            ("failed", "Payment Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_screenshot",
                    models.ImageField(blank=True, null=True, upload_to="payments/"),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("owner_remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="app.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("city", models.CharField(default="Shillong", max_length=100)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_owners/"
                    ),
                ),
                (
                    "id_proof",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_owners/id_proofs/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "upi_id",
                    models.CharField(
                        blank=True,
                        help_text="UPI ID for payments",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="Payment QR Code",
                        null=True,
                        upload_to="vehicle_owners/qr_codes/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_owner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="app.vehicleowner",
            ),
        ),
    ]
