# Generated by Django 6.0.3 on 2026-03-20 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_vehicle_vehiclebooking_vehicleowner_vehicle_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accommodation_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel"),
                            ("hostel", "Hostel"),
                            ("guest_house", "Guest House"),
                            ("homestay", "Homestay"),
                            ("resort", "Resort"),
                            ("lodge", "Lodge"),
                            ("cottage", "Cottage"),
                            ("apartment", "Apartment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the property", max_length=200),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Room"),
                            ("double", "Double Room"),
                            ("twin", "Twin Room"),
                            ("triple", "Triple Room"),
                            ("quad", "Quad Room"),
                            ("dormitory", "Dormitory"),
                            ("suite", "Suite"),
                            ("deluxe", "Deluxe Room"),
                            ("family", "Family Room"),
                        ],
                        default="double",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(default="Shillong", max_length=100)),
                ("landmark", models.CharField(blank=True, max_length=200, null=True)),
                ("google_maps_link", models.URLField(blank=True, null=True)),
                ("total_rooms", models.PositiveIntegerField(default=1)),
                ("available_rooms", models.PositiveIntegerField(default=1)),
                ("max_guests_per_room", models.PositiveIntegerField(default=2)),
                ("bed_count", models.PositiveIntegerField(default=1)),
                ("bathroom_attached", models.BooleanField(default=True)),
                ("wifi_available", models.BooleanField(default=False)),
                ("ac_available", models.BooleanField(default=False)),
                ("tv_available", models.BooleanField(default=False)),
                ("parking_available", models.BooleanField(default=False)),
                ("restaurant_available", models.BooleanField(default=False)),
                ("room_service", models.BooleanField(default=False)),
                ("laundry_service", models.BooleanField(default=False)),
                ("hot_water", models.BooleanField(default=True)),
                ("power_backup", models.BooleanField(default=False)),
                ("cctv", models.BooleanField(default=False)),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "extra_person_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("photo_1", models.ImageField(upload_to="accommodations/")),
                (
                    "photo_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="accommodations/"
                    ),
                ),
                (
                    "photo_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="accommodations/"
                    ),
                ),
                (
                    "photo_4",
                    models.ImageField(
                        blank=True, null=True, upload_to="accommodations/"
                    ),
                ),
                (
                    "photo_5",
                    models.ImageField(
                        blank=True, null=True, upload_to="accommodations/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "house_rules",
                    models.TextField(
                        blank=True,
                        help_text="Check-in/out times, pet policy, etc.",
                        null=True,
                    ),
                ),
                ("cancellation_policy", models.TextField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccommodationBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("number_of_rooms", models.PositiveIntegerField(default=1)),
                ("number_of_guests", models.PositiveIntegerField(default=1)),
                ("guest_name", models.CharField(max_length=100)),
                ("guest_phone", models.CharField(max_length=15)),
                (
                    "guest_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "guest_id_type",
                    models.CharField(
                        blank=True,
                        help_text="Aadhar, Passport, etc.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "guest_id_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("special_requests", models.TextField(blank=True, null=True)),
                ("number_of_nights", models.PositiveIntegerField(default=1)),
                ("room_charges", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "extra_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Payment Pending"),
                            ("submitted", "Payment Submitted"),
                            ("verified", "Payment Verified"),
                            ("failed", "Payment Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="accommodation_payments/"
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("owner_remarks", models.TextField(blank=True, null=True)),
                ("actual_check_in", models.DateTimeField(blank=True, null=True)),
                ("actual_check_out", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="app.accommodation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccommodationOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("owner_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("city", models.CharField(default="Shillong", max_length=100)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="accommodation_owners/"
                    ),
                ),
                (
                    "id_proof",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accommodation_owners/id_proofs/",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "upi_id",
                    models.CharField(
                        blank=True,
                        help_text="UPI ID for payments",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="Payment QR Code",
                        null=True,
                        upload_to="accommodation_owners/qr_codes/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_owner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="accommodation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accommodations",
                to="app.accommodationowner",
            ),
        ),
        migrations.CreateModel(
            name="AccommodationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5, help_text="Rating from 1 to 5"
                    ),
                ),
                ("review_text", models.TextField()),
                ("cleanliness_rating", models.PositiveIntegerField(default=5)),
                ("location_rating", models.PositiveIntegerField(default=5)),
                ("value_rating", models.PositiveIntegerField(default=5)),
                ("service_rating", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app.accommodation",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="app.accommodationbooking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
